package org.ricey_yam.lynxmind.client.ai.message.event.player;

public enum PlayerEventType {
    NONE,
    EVENT_PLAYER_CREATE_TASK,
    EVENT_PLAYER_REMOVE_TASK,
    EVENT_PLAYER_STATUS_HEARTBEAT,
    EVENT_PLAYER_PICKUP_ITEM,
    EVENT_PLAYER_BARITONE_TASK_STOP,
    EVENT_PLAYER_SCAN_BLOCK,
    EVENT_PLAYER_SCAN_ENTITY,
}
